name = "vynex-solutions"
pages_build_output_dir = "build/client"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]

[vars]
API_URL = "https://backend.vynexsoultions.com"
SITE_URL = "https://vynexsoultions.com"
